# Generated by Django 4.0.2 on 2022-03-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamFile',
            fields=[
                ('token', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('filePath', models.TextField()),
            ],
        ),
    ]
