# Generated by Django 4.0.2 on 2022-03-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamfile',
            old_name='filePath',
            new_name='filepath',
        ),
    ]
